name: Sanity checks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - run: chmod +x ./scripts/PRsanitycheck.py

      - run: ./scripts/PRsanitycheck.py
